language: php

php:
  - "8.1"

services:
  - redis

before_install:
  - cd app
  - sed -i 's/redis:6379/localhost/g' .env
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

script:
  - composer lint
  - composer php-cs-fixer
  - composer psalm
  - composer test