version: '3'

services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
#      - socket:/var/run
      - ./docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
      - ./app:/app
      - ./docker/nginx/certs:/etc/nginx/certs
    restart: always
    ports:
      - ${NGINX_LOCAL_HTTP_PORT}:80
      - ${NGINX_LOCAL_HTTPS_PORT}:443
    depends_on:
      - php-fpm
    networks:
      internal:
        ipv4_address: ${PROJECT_IP}
        aliases:
          - ${PROJECT_NAME}.local

  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: ./docker/php-fpm
      args:
        - USER_ID
        - GROUP_ID
    volumes:
#      - socket:/var/run
      - ./docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-dev.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./app:/app
    restart: always
    depends_on:
      - postgres
      - redis
#      - rabbit
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}
      PHP_IDE_CONFIG: serverName=${XDEBUG_IDE_SERVER_NAME}
    env_file:
      - .env
    networks:
      - internal

  php-cli:
    container_name: ${PROJECT_NAME}-php-cli
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: ./docker/php-fpm
      args:
        - USER_ID
        - GROUP_ID
    volumes:
#      - socket:/var/run
      - ./docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-dev.ini
      - ./docker/php-fpm/error_log.ini:/usr/local/etc/php/conf.d/error_log.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./app:/app
    restart: always
    depends_on:
      - postgres
      - redis
#      - rabbit
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}
      PHP_IDE_CONFIG: serverName=${XDEBUG_IDE_SERVER_NAME}
    env_file:
      - .env
    networks:
      - internal

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:12
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/data:/var/lib/postgresql/data
    shm_size: 512mb
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    env_file:
      - .env
    networks:
      - internal

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_LOCAL_PORT}:6379
    volumes:
      - ./docker/redis/data:/data
    networks:
      - internal

  rabbit:
    container_name: ${PROJECT_NAME}-rabbit
    hostname: rabbit
    image: rabbitmq:3.6.6-management
    volumes:
      - ./docker/rabbit/data:/var/lib/rabbitmq/mnesia/
    ports:
      - ${RABBIT_LOCAL_PORT}:5672
      - ${RABBIT_MANAGER_LOCAL_PORT}:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - .env
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_NAME}-mailhog
    ports:
      - ${MAILHOG_LOCAL_PORT}:1025
      - ${MAILHOG_MANAGER_PORT}:8025
    networks:
      - internal


#volumes:
#  socket:

networks:
  internal:
    driver: bridge
    name: ${PROJECT_NAME}_internal_network
    ipam:
      driver: default
      config:
        - subnet: ${PROJECT_SUBNET}
