version: '3'

services:
  nginx:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-nginx:${NGINX_IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    networks:
      - external
      - internal

  php-fpm:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-php-fpm:${PHP_FPM_IMAGE_TAG}
    restart: always
    networks:
      - internal

  php-workers:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-php-workers:${PHP_FPM_IMAGE_TAG}
    restart: always
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    networks:
      - internal

  rabbit:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-rabbit:${RABBITMQ_IMAGE_TAG}
    volumes:
      - ./volumes/rabbit/data:/var/lib/rabbitmq/mnesia/
    restart: always
    ports:
      - "${RABBIT_PORT}:5672"
      - "${RABBIT_MANAGER_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    networks:
      - internal

  redis:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-redis:${REDIS_IMAGE_TAG}
    volumes:
      - ./volumes/redis/data:/data
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command:
      - 'redis-server'
      - '--databases ${REDIS_DATABASES}'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass ${REDIS_PASSWORD}'
    networks:
      - internal

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true