{
 "title": "Geocoder",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(geocoder_geocode_internal_errors[1h])"
    }
   ]
  },
  {
   "title": "Error number",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "increase(geocoder_geocode_internal_errors[1h])"
    }
   ]
  },
  {
   "title": "Avg time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(geocoder_geocode_request_time)"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 4 },
   "targets": [
    {
     "expr": "avg(geocoder_geocode_request_time)"
    }
   ]
  },
  {
   "title": "Request number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(geocoder_geocode_request{qc=\"0\"}[1h]))",
     "legendFormat": "qc=0"
    },
    {
     "expr": "sum(increase(geocoder_geocode_request{qc=\"1\"}[1h]))",
     "legendFormat": "qc=1"
    },
    {
     "expr": "sum(increase(geocoder_geocode_request{qc=\"2\"}[1h]))",
     "legendFormat": "qc=2"
    },
    {
     "expr": "sum(increase(geocoder_geocode_request{qc=\"3\"}[1h]))",
     "legendFormat": "qc=3"
    }
   ]
  },
  {
   "title": "Slow avg time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(geocoder_geocode_slow_request_time)"
    }
   ]
  },
  {
   "title": "Slow request time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 13 },
   "targets": [
    {
     "expr": "avg(geocoder_geocode_slow_request_time)"
    }
   ]
  },
  {
   "title": "Slow request number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(geocoder_geocode_slow_request{qc=\"0\"}[1h]))",
     "legendFormat": "qc=0"
    },
    {
     "expr": "sum(increase(geocoder_geocode_slow_request{qc=\"1\"}[1h]))",
     "legendFormat": "qc=1"
    },
    {
     "expr": "sum(increase(geocoder_geocode_slow_request{qc=\"2\"}[1h]))",
     "legendFormat": "qc=2"
    },
    {
     "expr": "sum(increase(geocoder_geocode_slow_request{qc=\"3\"}[1h]))",
     "legendFormat": "qc=3"
    }
   ]
  }
 ]
}