services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\DataLoad\:
        resource: '../../../src/DataLoad/*'
        exclude:
            - '../../../src/DataLoad/{Domain,Test}'

    App\DataLoad\Infrastructure\Controller\:
        resource: '../../../src/DataLoad/Infrastructure/Controller'
        tags: ['controller.service_arguments']