version: '3'

services:
  nginx:
    image: cr.yandex/crpb3ivkntf2mnurlnuo/avitoparser-nginx:1.0.0
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  php-fpm:
    image: cr.yandex/crpb3ivkntf2mnurlnuo/avitoparser-php-fpm:1.0.0
    restart: always

  php-workers:
    image: cr.yandex/crpb3ivkntf2mnurlnuo/avitoparser-php-workers:1.0.0
    restart: always
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  rabbit:
    image: cr.yandex/crpb3ivkntf2mnurlnuo/avitoparser-rabbit:1.0.0
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 8ZmaPS5FKr3GYAd2