#cloud-config
runcmd:
  - [ sudo, chmod, 666, /dev/ttyS1]
users:
  - name: dev
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvC9b7XqFG0U5PX/qimxahuOKb19CvNaDKDUjkjO5+fYHwfEofVgYW/cHnqfHRPyGJ828Ea7p2XSulhbZyJ1If93pN7MHrRQmQkMhXinnrX2m1nx+fNDW1I7GeDaxshsJ6sy3Rhv8DOEHvTwRknW5iDruBmHJJqNM4U0zSJzTwt3ntwfY3ZeWOLIZjXkpP7QEJWYMRKjHYqzA1xBBLCB3W/YbbW+ke72YZ/sIqynAtaogBaw5DwQ1l5hrOCSLzcfT/IGLb0OQW9aeOt9SHJ1vH0vkDWNM8dj6Tyro0mdJzG39Q4igKp86YskSrKsF7CF+oxTumCUA6KIPdXvo2Xvysw== imported-openssh-key
