global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alerts/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbit'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:15692']

  - job_name: 'app'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:80']

