global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/prometheus_alerts/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'fias-gar-rabbit'
    static_configs:
      - targets: ['host.docker.internal:15692']

  - job_name: 'fias-gar-app'
    static_configs:
      - targets: ['host.docker.internal:80']

  - job_name: 'geocoder-app'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'geocoder-solr'
    static_configs:
      - targets: ['host.docker.internal:8983']