{
 "title": "FIAS Database Import",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "load_delta_version",
    "query": {
     "query": "query_result(fias_gar_load_version{type=\"delta\"})"
    }
   },
   {
    "name": "load_full_version",
    "query": {
     "query": "query_result(fias_gar_load_version{type=\"full\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Delta imports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Delta import objects",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_task_num{type=\"delta\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Save errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_save_error_num{type=\"delta\",version=\"$load_delta_version\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "fias_gar_parse_task_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_parse_success_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_parse_error_num{type=\"delta\",version=\"$load_delta_version\"}",
     "legendFormat": "parse {{version}}"
    },
    {
     "expr": "fias_gar_save_task_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_save_success_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_save_error_num{type=\"delta\",version=\"$load_delta_version\"}",
     "legendFormat": "save {{version}}"
    }
   ]
  },
  {
   "title": "Task per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(fias_gar_parse_task_num{type=\"delta\",version=\"$load_delta_version\"}[5m])",
     "legendFormat": "parse {{version}}"
    },
    {
     "expr": "rate(fias_gar_save_task_num{type=\"delta\",version=\"$load_delta_version\"}[5m])",
     "legendFormat": "save {{version}}"
    }
   ]
  },
  {
   "title": "Parse queue time to end",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fias_gar_parse_task_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_parse_success_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_parse_error_num{type=\"delta\",version=\"$load_delta_version\"}) / rate(fias_gar_parse_task_num{type=\"delta\",version=\"$load_delta_version\"}[5m])",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Parse errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_error_num{type=\"delta\",version=\"$load_delta_version\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Save queue time to end",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fias_gar_save_task_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_save_success_num{type=\"delta\",version=\"$load_delta_version\"} - fias_gar_save_error_num{type=\"delta\",version=\"$load_delta_version\"}) / rate(fias_gar_save_task_num{type=\"delta\",version=\"$load_delta_version\"}[5m])",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(fias_gar_save_task_num{type=\"delta\"}[5m])",
     "legendFormat": "save {{version}}"
    }
   ]
  },
  { "title": "Full imports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Full import objects",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_task_num{type=\"full\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Save errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_save_error_num{type=\"full\",version=\"$load_full_version\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "fias_gar_parse_task_num{type=\"full\",version=\"$load_full_version\"} - fias_gar_parse_success_num{type=\"full\",version=\"$load_full_version\"} - fias_gar_parse_error_num{type=\"full\",version=\"$load_full_version\"}",
     "legendFormat": "parse {{version}}"
    },
    {
     "expr": "fias_gar_save_task_num{type=\"full\",version=\"$load_full_version\"} - fias_gar_save_success_num{type=\"full\",version=\"$load_full_version\"} - fias_gar_save_error_num{type=\"full\",version=\"$load_full_version\"}",
     "legendFormat": "save {{version}}"
    }
   ]
  },
  {
   "title": "Task per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(fias_gar_parse_task_num{type=\"full\",version=\"$load_full_version\"}[5m])",
     "legendFormat": "parse {{version}}"
    },
    {
     "expr": "rate(fias_gar_save_task_num{type=\"full\",version=\"$load_full_version\"}[5m])",
     "legendFormat": "save {{version}}"
    }
   ]
  },
  {
   "title": "Save queue time to end",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fias_gar_save_task_num{type=\"full\",version=\"$load_full_version\"} - fias_gar_save_success_num{type=\"full\",version=\"$load_full_version\"} - fias_gar_save_error_num{type=\"full\",version=\"$load_full_version\"}) / rate(fias_gar_save_task_num{type=\"full\",version=\"$load_full_version\"}[5m])",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Parse errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_error_num{type=\"full\",version=\"$load_full_version\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Parse queue time to end",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fias_gar_parse_task_num{version=\"$load_delta_version\"} - fias_gar_parse_success_num{version=\"$load_delta_version\"} - fias_gar_parse_error_num{version=\"$load_delta_version\"}) / rate(fias_gar_parse_task_num{version=\"$load_delta_version\"}[5m])",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(fias_gar_save_task_num{type=\"full\"}[5m])",
     "legendFormat": "save {{version}}"
    }
   ]
  }
 ]
}