version: '3'

services:
  caddy:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-caddy:${CADDY_IMAGE_TAG}
    ports:
      - '${PROMETHEUS_PORT}:9090'
      - '${PUSHGATEWAY_PORT}:9091'
      - '${ALERTMANAGER_PORT}:9093'
    environment:
      - CADDY_ADMIN_USER=${CADDY_ADMIN_USER}
      - CADDY_ADMIN_PASSWORD=${CADDY_ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - monitor-net

  prometheus:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-prometheus:${PROMETHEUS_IMAGE_TAG}
    user: root
    volumes:
      - ./volumes/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - '9090'
    networks:
      - monitor-net

  pushgateway:
    container_name: monitor-pushgateway
    image: prom/pushgateway:v1.4.2
    restart: unless-stopped
    expose:
      - '9091'
    networks:
      - monitor-net

  alertmanager:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-alertmanager:${ALERTMANAGER_IMAGE_TAG}
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - '9093'
    networks:
      - monitor-net

  alertmanager-bot:
    container_name: monitor-alertmanager-bot
    image: metalmatze/alertmanager-bot:0.4.3
    command:
      - '--alertmanager.url=http://alertmanager:9093'
      - '--log.level=info'
      - '--store=bolt'
      - '--bolt.path=/data/bot.db'
    restart: unless-stopped
    environment:
      TELEGRAM_ADMIN: '${ALERTMANAGER_BOT_CHAT_ID}'
      TELEGRAM_TOKEN: '${ALERTMANAGER_BOT_TOKEN}'
    ports:
      - '8080:8080'
    volumes:
      - ./volumes/alertmanager-bot/data:/data
    networks:
      - monitor-net

  grafana:
    image: ${REGISTRY_ADDRESS}/${PROJECT_NAME}-grafana:${GRAFANA_IMAGE_TAG}
    user: root
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${GRAFANA_PORT}:3000'
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

