services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Auth\:
    resource: '../../src/Auth/*'

  App\Auth\Presentation\Controller\:
    resource: '../../src/Auth/Presentation/Controller'
    tags: ['controller.service_arguments']

  App\Auth\Infrastructure\Repository\UserFetcher: ~
  App\Auth\Domain\User\Repository\UserFetcherInterface: '@App\Auth\Infrastructure\Repository\UserFetcher'

  App\Auth\Infrastructure\Repository\UserRepository: ~
  App\Auth\Domain\User\Repository\UserRepositoryInterface: '@App\Auth\Infrastructure\Repository\UserRepository'

  App\Auth\Infrastructure\Service\PasswordHasher: ~
  App\Auth\Domain\User\Service\PasswordHasherInterface: '@App\Auth\Infrastructure\Service\PasswordHasher'

  App\Auth\Infrastructure\Service\PasswordGenerator: ~
  App\Auth\Domain\User\Service\PasswordGeneratorInterface: '@App\Auth\Infrastructure\Service\PasswordGenerator'

  App\Auth\Infrastructure\Service\Tokenizer:
    factory: ['App\Auth\Infrastructure\Service\TokenizerFactory', 'create']
    arguments: ['PT1H']
  App\Auth\Domain\User\Service\TokenizerInterface: '@App\Auth\Infrastructure\Service\Tokenizer'