monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_nested
            excluded_http_codes: [404, 405]
            buffer_size: 50
        main_nested:
            type: stream
            path: 'php://stderr'
            level: debug
#        sentry:
#            type: service
#            id: Sentry\Monolog\Handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]