{
 "title": "Imports",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Delta imports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Delta import objects",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_task_num{type=\"delta\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Delta import process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(fias_gar_parse_task_num{type=\"delta\"}[10m])",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Delta import parse errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_error_num{type=\"delta\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Delta import parse errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_error_num{type=\"delta\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Full imports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Full import objects",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_task_num{type=\"full\"} ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Full import process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(fias_gar_parse_task_num{type=\"full\"}[10m])",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Full import save errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_save_error_num{type=\"full\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Full import parse errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fias_gar_parse_error_num{type=\"full\"}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}