@startuml
'https://plantuml.com/component-diagram

() "Версия ФИАС" as Version
() "Данные ФИАС" as Data

component "Админка" {
    frame "Сервис" {
        [Настройки]
    }
    frame "Дополнение" {
      [Синонимы]
      [Координаты]
    }
    frame "Просмотр" {
      [Статистика]
      [Данные ФИАС]
    }
}

component "Загрузка ФИАС" {
    [Проверка версии] .up.> Version
    [Проверка версии] <-right- [Загрузка XML]
    [Загрузка XML] .up.> Data
    [Загрузка XML] <-- [Разбор XML]
    [Разбор XML]
    [Загрузка в БД]

    database "Rabbit" {
        [Очередь разбора]
        [Очередь загрузки в БД]
    }

    [Разбор XML] <-- [Очередь разбора]
    [Загрузка в БД] --> [Очередь загрузки в БД]
    [Очередь загрузки в БД] --> [Очередь разбора]
}

database "Postgres" {
    rectangle "fias_gar_*" #White
    rectangle "ext_*" #White
    rectangle "user" #White
    rectangle "token" #White
}

component "API" {
    [fias_gar_*] <-- [Методы API]
    [ext_*] <-- [Методы API]
    [Методы API]
}

component "Авторизация" {
    [Пользователи] -up-> [user]
    [Токены] -up-> [token]
    [token] --> [Пользователи]
}

[Методы API] --> [Токены]
[Загрузка в БД] <-up- [fias_gar_*]
[Координаты] --> [ext_*]
[Синонимы] --> [ext_*]
[Данные ФИАС] --> [fias_gar_*]
[Статистика] --> [fias_gar_*]
[Настройки] --> [user]

@enduml