@startuml
'https://plantuml.com/component-diagram

() "Версия ФИАС" as Version
() "Данные ФИАС" as Data

component "Админка" {
    frame "Сервис" {
        [Настройки]
    }
    frame "Дополнение" {
      [Синонимы]
      [Координаты]
    }
    frame "Просмотр" {
      [Статистика]
      [Данные ФИАС]
    }
}

component "Загрузка ФИАС" {
    [Проверка версии] .up.> Version
    [Проверка версии] <-right- [Загрузка XML]
    [Загрузка XML] .up.> Data
    [Загрузка XML] <-- [Разбор XML]
    [Разбор XML]
    [Загрузка в БД]

    database "Rabbit" {
        [Очередь разбора]
        [Очередь загрузки в БД]
    }

    [Разбор XML] <-- [Очередь разбора]
    [Загрузка в БД] --> [Очередь загрузки в БД]
    [Очередь загрузки в БД] --> [Очередь разбора]
}

database "Postgres" {
    rectangle "Таблицы fias_gar_*" #White
    rectangle "Таблицы ext_*" #White
    rectangle "Users" #White
    rectangle "Tokens" #White
}

component "API" {
    [Таблицы fias_gar_*] <-- [Методы API]
    [Таблицы ext_*] <-- [Методы API]
    [Методы API]
}

component "Авторизация" {
    [Пользователи] -up-> [Users]
    [Токены] -up-> [Tokens]
    [Tokens] --> [Пользователи]
}


[Загрузка в БД] <-up- [Таблицы fias_gar_*]
[Методы API] --> [Токены]
[Координаты] --> [Таблицы ext_*]
[Синонимы] --> [Таблицы ext_*]
[Данные ФИАС] --> [Таблицы fias_gar_*]
[Статистика] --> [Таблицы fias_gar_*]
[Настройки] --> [Users]




@enduml