doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:         pdo_pgsql
                dbname:         '%env(POSTGRES_DB)%'
                user:           '%env(POSTGRES_USER)%'
                password:       '%env(POSTGRES_PASSWORD)%'
                host:           '%env(POSTGRES_HOST)%'
                port:           '%env(POSTGRES_PORT)%'
                server_version: '%env(POSTGRES_SERVER_VERSION)%'
                schema_filter:  ~^(?!fias_|v_)~

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

#        metadata_cache_driver:
#            type: pool
#            pool: doctrine.cache.redis
#        query_cache_driver:
#            type: pool
#            pool: doctrine.cache.redis
#        result_cache_driver:
#            type: pool
#            pool: doctrine.cache.redis