doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: ~^(?!fias_|v_)~

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

#        metadata_cache_driver:
#            type: service
#            id: doctrine.cache.redis
#        query_cache_driver:
#            type: service
#            id: doctrine.cache.redis
#        result_cache_driver:
#            type: service
#            id: doctrine.cache.redis

#services:
#    redis.doctrine:
#        class: Redis
#        factory: Symfony\Component\Cache\Adapter\RedisAdapter::createConnection
#        arguments:
#            - '%env(REDIS_DSN)%'
#
#    doctrine.cache.redis:
#        class: Doctrine\Common\Cache\RedisCache
#        calls:
#            - ['setRedis', ['@redis.doctrine']]