framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        failure_transport: failed

        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        transports:
             failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
             sync: 'sync://'
             async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                serializer: messenger.transport.symfony_serializer


        routing:
             'App\Shared\Domain\Bus\Command\CommandInterface': sync
             'App\Shared\Domain\Bus\Query\QueryInterface': sync
             'App\Shared\Domain\Bus\Event\EventInterface': sync
