framework:
    messenger:
        failure_transport: failed

        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        transports:
            sync: 'sync://'
            postgresql_command:
                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    queue_name: command
            postgresql_event:
                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    queue_name: event
            rabbit_command:
                dsn: '%env(MESSENGER_RABBIT_TRANSPORT_DSN)%'
                options:
                    queues:
                        command: ~
            rabbit_event:
                dsn: '%env(MESSENGER_RABBIT_TRANSPORT_DSN)%'
                options:
                    queues:
                        event: ~
            failed: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%?queue_name=failed'

        routing:
            'App\Shared\Domain\Bus\Command\CommandInterface': sync
            'App\Shared\Domain\Bus\Query\QueryInterface': sync
            'App\Shared\Domain\Bus\Event\EventInterface': postgresql_command
