monolog:
    handlers:
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            level: INFO
            channels: ["php"]
            bubble: false
