monolog:
    channels: ["deprecation"]
    handlers:
        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/deprecations.log"
            channels: ["deprecation"]
            bubble: false
            max_files: 1
