security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            id: App\Auth\Infrastructure\Security\AuthIdentityProvider
#        app_admin_provider:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_secured_area:
            pattern:   ^/admin
#            anonymous: false
            user_checker: App\Auth\Infrastructure\Security\AuthIdentityChecker
            lazy: true
            provider: app_user_provider

            form_login:
                check_path: app_login
                login_path: app_login
                enable_csrf: true

            logout:
                path: app_logout
                target: main

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                check_path: app_login
                login_path: app_login
                enable_csrf: true

#        admin_secured_area:
#            pattern:   ^/admin
#            anonymous: false
#            lazy: true
#            provider: app_admin_provider
#            guard:
#                authenticators:
#                    - App\Security\AdminAuthenticator
#            logout:
#                path: admin_logout
#                target: /admin/login
#
#            switch_user:  { role: ROLE_SUPER_ADMIN, parameter: _impersonate }
#
#        api_secured_area:
#            pattern:   ^/api
#            stateless: true
#            anonymous: false
#            provider: app_user_provider
#            guard:
#                authenticators:
#                    - App\Security\ApiTokenAuthenticator
#
##        user_secured_area:
##            pattern:   ^/
##            anonymous: true
##            provider: app_user_provider
##            guard:
##                authenticators:
##                    - App\Security\UserAuthenticator
##                entry_point: App\Security\UserAuthenticator
#
#            # activate different ways to authenticate
#            # https://symfony.com/doc/current/security.html#firewalls-authentication
#
#            # https://symfony.com/doc/current/security/impersonating_user.html
#            # switch_user: true
#
#    # Easy way to control access for large sections of your site
#    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER