services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../../src/Shared/*'

    App\Shared\Infrastructure\Symfony\FixDefaultSchemaSubscriber:
        tags: [{ name: doctrine.event_subscriber, connection: default }]

    Redis:
        class: Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'
            - auth:
                  - '%env(REDIS_PASSWORD)%'

    App\Shared\Infrastructure\Persistence\DoctrineFlusher: ~
    App\Shared\Domain\Persistence\FlusherInterface: '@App\Shared\Infrastructure\Persistence\DoctrineFlusher'
    
    App\Shared\Infrastructure\Bus\Command\CommandBus: ~
    App\Shared\Domain\Bus\Command\CommandBusInterface: '@App\Shared\Infrastructure\Bus\Command\CommandBus'

    App\Shared\Infrastructure\Bus\Query\QueryBus: ~
    App\Shared\Domain\Bus\Query\QueryBusInterface: '@App\Shared\Infrastructure\Bus\Query\QueryBus'

    App\Shared\Infrastructure\Bus\Event\EventBus: ~
    App\Shared\Domain\Bus\Event\EventBusInterface: '@App\Shared\Infrastructure\Bus\Event\EventBus'

