services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../../src/Shared/*'

    App\Shared\Infrastructure\Symfony\FixDefaultSchemaSubscriber:
        tags: [{ name: doctrine.event_subscriber, connection: default }]
    
    App\Shared\Infrastructure\Bus\Command\CommandBus: ~