parameters:
    fias_version_list_url: 'https://fias.nalog.ru/WebServices/Public/GetAllDownloadFileInfo'

    fias_url_version_format: 'Y.m.d'
    fias_url_xml: 'https://fias.nalog.ru/downloads/#version#'
    fias_url_full_file: 'gar_xml.zip'
    fias_url_delta_file: 'gar_delta_xml.zip'
    fias_url_full_xml: '%fias_url_xml%/%fias_url_full_file%'
    fias_url_delta_xml: '%fias_url_xml%/%fias_url_delta_file%'

    fias_zip_directory: '%kernel.project_dir%/var/zip'
    fias_zip_max_full_file: 2
    fias_zip_max_delta_file: 3
    fias_zip_reload_if_exists: false
    fias_zip_exclude_patterns:
        addr_obj: '*_ADDR_OBJ_[0-9]*'
        addr_obj_division: '*_ADDR_OBJ_DIVISION_[0-9]*'
        addr_obj_params: '*_ADDR_OBJ_PARAMS_[0-9]*'
        adm_hierarchy: '*_ADM_HIERARCHY_[0-9]*'
        apartments: '*_APARTMENTS_[0-9]*'
        apartments_params: '*_APARTMENTS_PARAMS_[0-9]*'
        carplaces: '*_CARPLACES_[0-9]*'
        carplaces_params: '*_CARPLACES_PARAMS_[0-9]*'
        change_history: '*_CHANGE_HISTORY_[0-9]*'
        houses: '*_HOUSES_[0-9]*'
        houses_params: '*_HOUSES_PARAMS_[0-9]*'
        mun_hierarchy: '*_MUN_HIERARCHY_[0-9]*'
        normative_docs: '*_NORMATIVE_DOCS_[0-9]*'
        reestr_objects: '*_REESTR_OBJECTS_[0-9]*'
        rooms: '*_ROOMS_[0-9]*'
        rooms_params: '*_ROOMS_PARAMS_[0-9]*'
        steads: '*_STEADS_[0-9]*'
        steads_params: '*_STEADS_PARAMS_[0-9]*'
        addhouse_types: '*_ADDHOUSE_TYPES_[0-9]*'
        addr_obj_types: '*_ADDR_OBJ_TYPES_[0-9]*'
        apartment_types: '*_APARTMENT_TYPES_[0-9]*'
        house_types: '*_HOUSE_TYPES_[0-9]*'
        normative_docs_kinds: '*_NORMATIVE_DOCS_KINDS_[0-9]*'
        normative_docs_types: '*_NORMATIVE_DOCS_TYPES_[0-9]*'
        object_levels: '*_OBJECT_LEVELS_[0-9]*'
        operation_types: '*_OPERATION_TYPES_[0-9]*'
        param_types: '*_PARAM_TYPES_[0-9]*'
        room_types: '*_ROOM_TYPES_[0-9]*'

    fias_xml_directory: '%kernel.project_dir%/var/xml'

    fias_tables_pkey:
        object_levels: 'level'
        reestr_objects: 'objectid'

    fias_tables:
        addr_obj: 'fias_gar_addrobj'
        addr_obj_division: 'fias_gar_addrobjdivision'
        addr_obj_params: 'fias_gar_addrobjparam'
        adm_hierarchy: 'fias_gar_admhierarchy'
        apartments: 'fias_gar_apartments'
        apartments_params: 'fias_gar_apartmentsparam'
        carplaces: 'fias_gar_carplaces'
        carplaces_params: 'fias_gar_carplacesparam'
        change_history: 'fias_gar_changehistory'
        houses: 'fias_gar_houses'
        houses_params: 'fias_gar_housesparam'
        mun_hierarchy: 'fias_gar_munhierarchy'
        normative_docs: 'fias_gar_normativedocs'
        reestr_objects: 'fias_gar_reestrobjects'
        rooms: 'fias_gar_rooms'
        rooms_params: 'fias_gar_roomsparam'
        steads: 'fias_gar_steads'
        steads_params: 'fias_gar_steadsparam'
        addhouse_types: 'fias_gar_housetypes'
        addr_obj_types: 'fias_gar_addrobjtypes'
        apartment_types: 'fias_gar_apartmenttypes'
        house_types: 'fias_gar_housetypes'
        normative_docs_kinds: 'fias_gar_normativedocskinds'
        normative_docs_types: 'fias_gar_normativedocstypes'
        object_levels: 'fias_gar_objectlevels'
        operation_types: 'fias_gar_operationtypes'
        param_types: 'fias_gar_paramtypes'
        room_types: 'fias_gar_roomtypes'

    fias_tags:
        addr_obj: 'OBJECT'
        addr_obj_division: 'ITEM'
        addr_obj_params: 'PARAM'
        adm_hierarchy: 'ITEM'
        apartments: 'APARTMENT'
        apartments_params: 'PARAM'
        carplaces: 'CARPLACE'
        carplaces_params: 'PARAM'
        change_history: 'ITEM'
        houses: 'HOUSE'
        houses_params: 'PARAM'
        mun_hierarchy: 'ITEM'
        normative_docs: 'NORMDOC'
        reestr_objects: 'OBJECT'
        rooms: 'ROOM'
        rooms_params: 'PARAM'
        steads: 'STEAD'
        steads_params: 'PARAM'
        addhouse_types: 'HOUSETYPE'
        addr_obj_types: 'ADDRESSOBJECTTYPE'
        apartment_types: 'APARTMENTTYPE'
        house_types: 'HOUSETYPE'
        normative_docs_kinds: 'NDOCKIND'
        normative_docs_types: 'NDOCTYPE'
        object_levels: 'OBJECTLEVEL'
        operation_types: 'OPERATIONTYPE'
        param_types: 'PARAMTYPE'
        room_types: 'ROOMTYPE'

    fias_import_tokens:
        - object_levels
        - operation_types
        - addr_obj
        - addr_obj_division
        - addr_obj_types
        - addhouse_types
        - house_types
        - houses
        - adm_hierarchy
        - mun_hierarchy

#        - addr_obj_params
#        - apartments
#        - apartments_params
#        - carplaces
#        - carplaces_params
#        - change_history
#        - houses_params
#        - normative_docs
#        - reestr_objects
#        - rooms
#        - rooms_params
#        - steads
#        - steads_params
#        - apartment_types
#        - normative_docs_kinds
#        - normative_docs_types
#        - param_types
#        - room_types

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $xmlDirectory: '%fias_xml_directory%'
            $zipDirectory: '%fias_zip_directory%'
            $importTokens: '%fias_import_tokens%'
            $fullFileName: '%fias_url_full_file%'
            $deltaFileName: '%fias_url_delta_file%'

    App\DataLoad\:
        resource: '../../src/DataLoad/*'

    App\DataLoad\Presentation\Controller\:
        resource: '../../src/DataLoad/Presentation/Controller'
        tags: ['controller.service_arguments']

    App\DataLoad\Infrastructure\Service\DataDownloader:
        arguments:
            $versionFormat: '%fias_url_version_format%'
            $urlFullXml: '%fias_url_full_xml%'
            $urlDeltaXml: '%fias_url_delta_xml%'
    App\DataLoad\Application\Service\DataDownloaderInterface: '@App\DataLoad\Infrastructure\Service\DataDownloader'

    App\DataLoad\Infrastructure\Service\DataExtractor: ~
    App\DataLoad\Application\Service\DataExtractorInterface: '@App\DataLoad\Infrastructure\Service\DataExtractor'

    App\DataLoad\Infrastructure\Service\ZipFileRotator:
        arguments:
            $maxFullFileNum: '%fias_zip_max_full_file%'
            $maxDeltaFileNum: '%fias_zip_max_delta_file%'
    App\DataLoad\Domain\ZipFile\Service\ZipFileRotatorInterface: '@App\DataLoad\Infrastructure\Service\ZipFileRotator'

    App\DataLoad\Infrastructure\Service\ZipFileExtractor:
        arguments:
            $excludes: '%fias_zip_exclude_patterns%'
            $importTokens: '%fias_import_tokens%'
    App\DataLoad\Domain\ZipFile\Service\ZipFileExtractorInterface: '@App\DataLoad\Infrastructure\Service\ZipFileExtractor'

    App\DataLoad\Infrastructure\Service\ZipFileLoader:
        arguments:
            $reloadIfExists: '%fias_zip_reload_if_exists%'
    App\DataLoad\Domain\ZipFile\Service\ZipFileLoaderInterface: '@App\DataLoad\Infrastructure\Service\ZipFileLoader'

    App\DataLoad\Infrastructure\Service\XmlFileCleaner: ~
    App\DataLoad\Domain\XmlFile\Service\XmlFileCleanerInterface: '@App\DataLoad\Infrastructure\Service\XmlFileCleaner'

    App\DataLoad\Infrastructure\Service\XmlFileFinder: ~
    App\DataLoad\Domain\XmlFile\Service\XmlFileFinderInterface: '@App\DataLoad\Infrastructure\Service\XmlFileFinder'

    App\DataLoad\Infrastructure\Service\TagGenerator: ~
    App\DataLoad\Domain\Tag\Service\TagGeneratorInterface: '@App\DataLoad\Infrastructure\Service\TagGenerator'

    App\DataLoad\Infrastructure\Service\TagSaver: ~
    App\DataLoad\Domain\Tag\Service\TagSaverInterface: '@App\DataLoad\Infrastructure\Service\TagSaver'

    App\DataLoad\Infrastructure\Service\TagParser: ~
    App\DataLoad\Domain\Tag\Service\TagParserInterface: '@App\DataLoad\Infrastructure\Service\TagParser'

    App\DataLoad\Infrastructure\Service\TableColumner: ~
    App\DataLoad\Domain\Table\Service\TableColumnerInterface: '@App\DataLoad\Infrastructure\Service\TableColumner'

    App\DataLoad\Infrastructure\Service\VersionLoader:
        arguments:
            $versionListUrl: '%fias_version_list_url%'
    App\DataLoad\Domain\Version\Service\VersionLoaderInterface: '@App\DataLoad\Infrastructure\Service\VersionLoader'

    App\DataLoad\Infrastructure\Service\VersionDecoder: ~
    App\DataLoad\Domain\Version\Service\VersionDecoderInterface: '@App\DataLoad\Infrastructure\Service\VersionDecoder'

    App\DataLoad\Infrastructure\Repository\VersionRepository: ~
    App\DataLoad\Domain\Version\Repository\VersionRepositoryInterface: '@App\DataLoad\Infrastructure\Repository\VersionRepository'

    App\DataLoad\Infrastructure\Service\VersionListRefresher: ~
    App\DataLoad\Application\Service\VersionListRefresherInterface: '@App\DataLoad\Infrastructure\Service\VersionListRefresher'

    App\DataLoad\Infrastructure\Service\ImportCounterIncrementor:
        arguments:
            $redis: '@Redis'
    App\DataLoad\Domain\Import\Service\ImportCounterIncrementorInterface: '@App\DataLoad\Infrastructure\Service\ImportCounterIncrementor'

    App\DataLoad\Infrastructure\Repository\ImportRedisRepository:
        arguments:
            $redis: '@Redis'
    App\DataLoad\Domain\Import\Repository\ImportRepositoryInterface: '@App\DataLoad\Infrastructure\Repository\ImportRedisRepository'

    App\DataLoad\Infrastructure\Repository\VersionFetcher: ~
    App\DataLoad\Domain\Version\Repository\VersionFetcherInterface: '@App\DataLoad\Infrastructure\Repository\VersionFetcher'

    App\DataLoad\Infrastructure\Service\NextVersionFinder: ~
    App\DataLoad\Domain\Version\Service\NextVersionFinderInterface: '@App\DataLoad\Infrastructure\Service\NextVersionFinder'

    App\DataLoad\Infrastructure\Service\VersionCoverer: ~
    App\DataLoad\Domain\Version\Service\VersionCovererInterface: '@App\DataLoad\Infrastructure\Service\VersionCoverer'

    App\DataLoad\Infrastructure\Repository\ImportRedisFetcher: ~
    App\DataLoad\Domain\Import\Repository\ImportFetcherInterface: '@App\DataLoad\Infrastructure\Repository\ImportRedisFetcher'

    App\DataLoad\Infrastructure\Service\LoadTryIncrementor: ~
    App\DataLoad\Domain\Version\Service\LoadTryIncrementorInterface: '@App\DataLoad\Infrastructure\Service\LoadTryIncrementor'

    App\DataLoad\Infrastructure\Service\ZipFileNamer: ~
    App\DataLoad\Domain\ZipFile\Service\ZipFileNamerInterface: '@App\DataLoad\Infrastructure\Service\ZipFileNamer'
