parameters:
    fias_all_version_url: 'https://fias.nalog.ru/WebServices/Public/GetAllDownloadFileInfo'

    fias_url_version_format: 'Y.m.d'
    fias_url_xml: 'https://fias.nalog.ru/downloads/#version#'
    fias_url_full_file: 'gar_xml.zip'
    fias_url_delta_file: 'gar_delta_xml.zip'
    fias_url_full_xml: '%fias_url_xml%/%fias_url_full_file%'
    fias_url_delta_xml: '%fias_url_xml%/%fias_url_delta_file%'

    fias_zip_directory: '%kernel.project_dir%/var/zip'
    fias_zip_max_full_file: 1
    fias_zip_max_delta_file: 2
    fias_xml_directory: '%kernel.project_dir%/var/xml'

    fias_tables_pkey:
        object_levels: 'level'
        reestr_objects: 'objectid'

    fias_tables:
        addr_obj: 'fias_gar_addrobj'
        addr_obj_division: 'fias_gar_addrobjdivision'
        addr_obj_params: 'fias_gar_param'
        adm_hierarchy: 'fias_gar_admhierarchy'
        apartments: 'fias_gar_apartments'
        apartments_params: 'fias_gar_param'
        carplaces: 'fias_gar_carplaces'
        carplaces_params: 'fias_gar_param'
        change_history: 'fias_gar_changehistory'
        houses: 'fias_gar_houses'
        houses_params: 'fias_gar_param'
        mun_hierarchy: 'fias_gar_munhierarchy'
        normative_docs: 'fias_gar_normativedocs'
        reestr_objects: 'fias_gar_reestrobjects'
        rooms: 'fias_gar_rooms'
        rooms_params: 'fias_gar_param'
        steads: 'fias_gar_steads'
        steads_params: 'fias_gar_param'
        addhouse_types: 'fias_gar_housetypes'
        addr_obj_types: 'fias_gar_addrobjtypes'
        apartment_types: 'fias_gar_apartmenttypes'
        house_types: 'fias_gar_housetypes'
        normative_docs_kinds: 'fias_gar_normativedocskinds'
        normative_docs_types: 'fias_gar_normativedocstypes'
        object_levels: 'fias_gar_objectlevels'
        operation_types: 'fias_gar_operationtypes'
        param_types: 'fias_gar_paramtypes'
        room_types: 'fias_gar_roomtypes'

    fias_tags:
        addr_obj: 'OBJECT'
        addr_obj_division: 'ITEM'
        addr_obj_params: 'PARAM'
        adm_hierarchy: 'ITEM'
        apartments: 'APARTMENT'
        apartments_params: 'PARAM'
        carplaces: 'CARPLACE'
        carplaces_params: 'PARAM'
        change_history: 'ITEM'
        houses: 'HOUSE'
        houses_params: 'PARAM'
        mun_hierarchy: 'ITEM'
        normative_docs: 'NORMDOC'
        reestr_objects: 'OBJECT'
        rooms: 'ROOM'
        rooms_params: 'PARAM'
        steads: 'STEAD'
        steads_params: 'PARAM'
        addhouse_types: 'HOUSETYPE'
        addr_obj_types: 'ADDRESSOBJECTTYPE'
        apartment_types: 'APARTMENTTYPE'
        house_types: 'HOUSETYPE'
        normative_docs_kinds: 'NDOCKIND'
        normative_docs_types: 'NDOCTYPE'
        object_levels: 'OBJECTLEVEL'
        operation_types: 'OPERATIONTYPE'
        param_types: 'PARAMTYPE'
        room_types: 'ROOMTYPE'

    fias_import_tokens:
        - 'object_levels'
        - 'operation_types'
        - 'addr_obj'
        - 'adm_hierarchy'
        - 'mun_hierarchy'
        - 'addr_obj_types'
        - 'houses'
        - 'addhouse_types'
        - 'house_types'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $xmlDirectory: '%fias_xml_directory%'
            $zipDirectory: '%fias_zip_directory%'
            $importTokens: '%fias_import_tokens%'

    App\DataLoad\:
        resource: '../../src/DataLoad/*'

    App\DataLoad\Presentation\Controller\:
        resource: '../../src/DataLoad/Presentation/Controller'
        tags: ['controller.service_arguments']

    App\DataLoad\Infrastructure\Service\XmlDownloader:
        arguments:
            $versionFormat: '%fias_url_version_format%'
            $urlFullXml: '%fias_url_full_xml%'
            $urlDeltaXml: '%fias_url_delta_xml%'
    App\DataLoad\Application\Service\XmlDownloaderInterface: '@App\DataLoad\Infrastructure\Service\XmlDownloader'

    App\DataLoad\Infrastructure\Service\ZipFileRotator:
        arguments:
            $fullFileName: '%fias_url_full_file%'
            $deltaFileName: '%fias_url_delta_file%'
            $maxFullFileNum: '%fias_zip_max_full_file%'
            $maxDeltaFileNum: '%fias_zip_max_delta_file%'
    App\DataLoad\Domain\ZipFile\Service\ZipFileRotatorInterface: '@App\DataLoad\Infrastructure\Service\ZipFileRotator'

    App\DataLoad\Infrastructure\Service\ZipFileExtractor: ~
    App\DataLoad\Domain\ZipFile\Service\ZipFileExtractorInterface: '@App\DataLoad\Infrastructure\Service\ZipFileExtractor'

    App\DataLoad\Infrastructure\Service\ZipFileLoader: ~
    App\DataLoad\Domain\ZipFile\Service\ZipFileLoaderInterface: '@App\DataLoad\Infrastructure\Service\ZipFileLoader'

    App\DataLoad\Infrastructure\Service\XmlFileCleaner: ~
    App\DataLoad\Domain\XmlFile\Service\XmlFileCleanerInterface: '@App\DataLoad\Infrastructure\Service\XmlFileCleaner'

    App\DataLoad\Infrastructure\Service\XmlFileFinder: ~
    App\DataLoad\Domain\XmlFile\Service\XmlFileFinderInterface: '@App\DataLoad\Infrastructure\Service\XmlFileFinder'

    App\DataLoad\Infrastructure\Service\TagGenerator: ~
    App\DataLoad\Domain\Tag\Service\TagGeneratorInterface: '@App\DataLoad\Infrastructure\Service\TagGenerator'

    App\DataLoad\Infrastructure\Service\TagSaver: ~
    App\DataLoad\Domain\Tag\Service\TagSaverInterface: '@App\DataLoad\Infrastructure\Service\TagSaver'

    App\DataLoad\Infrastructure\Service\TagParser: ~
    App\DataLoad\Domain\Tag\Service\TagParserInterface: '@App\DataLoad\Infrastructure\Service\TagParser'

    App\DataLoad\Infrastructure\Service\TableColumner: ~
    App\DataLoad\Domain\Table\Service\TableColumnerInterface: '@App\DataLoad\Infrastructure\Service\TableColumner'

    App\DataLoad\Infrastructure\Service\VersionLoader:
        arguments:
            $allVersionUrl: '%fias_all_version_url%'
    App\DataLoad\Domain\Version\Service\VersionLoaderInterface: '@App\DataLoad\Infrastructure\Service\VersionLoader'

    App\DataLoad\Infrastructure\Service\VersionDecoder: ~
    App\DataLoad\Domain\Version\Service\VersionDecoderInterface: '@App\DataLoad\Infrastructure\Service\VersionDecoder'

    App\DataLoad\Infrastructure\Service\VersionRepository: ~
    App\DataLoad\Domain\Version\Entity\VersionRepositoryInterface: '@App\DataLoad\Infrastructure\Service\VersionRepository'

    App\DataLoad\Infrastructure\Service\VersionDownloader: ~
    App\DataLoad\Application\Service\VersionDownloaderInterface: '@App\DataLoad\Infrastructure\Service\VersionDownloader'