services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\DataLoad\:
        resource: '../../src/DataLoad/*'

    App\DataLoad\Presentation\Controller\:
        resource: '../../src/DataLoad/Presentation/Controller'
        tags: ['controller.service_arguments']
